# ==========================================
# SERVIDOR 1: FRONTEND (Puerto interno 80)
# ==========================================
server {
    listen 80;
    server_name localhost;
    
    # El universo aislado de tu frontend
    root /var/www/html/frontend/public;
    index index.php index.html;

    # 1. LA REGLA MAESTRA DE NAVEGACIÓN (La que te faltaba)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 2. EL PROCESADOR DE PHP
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # 3. LA OPTIMIZACIÓN DE ASSETS
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
        log_not_found off;
    }

    # EXCEPCIÓN: PARA QUE NO DETECTE ESTA RUTA COMO SI FUERA UN ASSET
    location ^~ /admin/cedulas/ {
        try_files $uri /index.php?$query_string;
    }

    # 4. EL BLINDAJE DE SEGURIDAD
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}

# ==========================================
# SERVIDOR 2: BACKEND API (Puerto interno 81)
# ==========================================
server {
    listen 81;
    server_name localhost;
    
    # Apuntamos a la carpeta public de TU backend
    root /var/www/html/backend/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}